### ISSUE TITLE
Upload failing

### ISSUE THREAD

**Issue by infiniteproject** [gilbertchen/duplicacy-cli#39]
Last backup failed with:

2017-01-07 11:04:58.163 ERROR UPLOAD_CHUNK Failed to upload the chunk 5148711fa98f182c9fadb05d881b27a3be1fdd396259180f736a96e48c5e2c31:
goroutine 37 [running]:
runtime/debug.Stack(0x41c568, 0xc420495ad0, 0xc420495ab0)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/gilbertchen/duplicacy.CatchLogException()
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/duplicacy_log.go:161 +0x196
panic(0x8dc160, 0xc4305e2480)
        /usr/local/go/src/runtime/panic.go:458 +0x243
github.com/gilbertchen/duplicacy.logf(0x2, 0x9342f1, 0xc, 0x940223, 0x21, 0xc420495f30, 0x2, 0x2)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/duplicacy_log.go:147 +0x1d8
github.com/gilbertchen/duplicacy.LOG_ERROR(0x9342f1, 0xc, 0x940223, 0x21, 0xc420495f30, 0x2, 0x2)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/duplicacy_log.go:93 +0x73
github.com/gilbertchen/duplicacy.(*BackupManager).UploadChunk.func1(0xc430138010, 0xc4203c6060, 0xc422e87d00, 0xc420138000, 0xc42e3d0051, 0x48, 0xc422e87cc0, 0x40)
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/duplicacy_backupmanager.go:1745 +0x1fc
created by github.com/gilbertchen/duplicacy.(*BackupManager).UploadChunk
        /Users/chgang/zincbox/go/src/github.com/gilbertchen/duplicacy/duplicacy_backupmanager.go:1752 +0x6fa

**Comment by gilbertchen** [comment]
Which storage backend are you using?

**Comment by infiniteproject** [comment]
Dropbox

**Comment by infiniteproject** [comment]
Backup keeps failing: actually any operation involving file (not directory) creation fails with Dropbox backend. I tried to reset token, create new app, etc with no success. List, cat, prune, history, diff, restore and check are working with the previously created backups. Init just creates the dopbox://dir and fails (no files inside). Any clues?
